services:
  mongodb:
    image: mongo:latest
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_INITDB_ROOT_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_INITDB_ROOT_PASSWORD}
    volumes:
      - mongo-data:/data/db

  webapp:
    image: ${PREDICTON_CONTAINER}
    depends_on:
      - mongodb
    environment:
      - URL_MONGO=mongodb://${MONGO_INITDB_ROOT_USERNAME}:${MONGO_INITDB_ROOT_PASSWORD}@mongodb:27017

  frontend:
    build: ./src/frontend
    ports:
      - 9000:8501
    environment:
      - API_URL=http://webapp:8000
    depends_on:
      - webapp

volumes:
  mongo-data:
